# 创建思源docker项目目录
- name: Create SiYuan directory
  file:
    path: "{{ siyuan_dir }}"
    state: directory
    mode: '0755'
    become: yes

# 配置思源docker-compose.yml
- name: Copy SiYuan Docker Compose file
  template:
    src: docker-compose.yml.j2
    dest: "{{ siyuan_dir }}/docker-compose.yml"
    become: yes

# 启动思源docker容器
- name: Start SiYuan Docker containers
  docker_compose:
    project_name: siyuan
    file: "{{ siyuan_dir }}/docker-compose.yml"
    become: yes